# One shared dev JWT keypair so the whole team's tokens interoperate and
# survive cluster rebuilds — that's the point of a shared environment. It
# lands in state; state lives in a private, versioned GCS bucket. Acceptable
# for a dev key only — the real keypair is still generated by hand per
# services/auth/README.md.
resource "tls_private_key" "jwt" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

locals {
  database_url = "postgresql+psycopg://${google_sql_user.medstock.name}:${random_password.db.result}@${google_sql_database_instance.dev.private_ip_address}:5432/${google_sql_database.medstock.name}"

  secret_values = {
    "medstock-dev-db-url"          = local.database_url
    "medstock-dev-jwt-private-key" = tls_private_key.jwt.private_key_pem
    "medstock-dev-jwt-public-key"  = tls_private_key.jwt.public_key_pem
    "medstock-dev-gemini-api-key"  = var.gemini_api_key
  }
}

resource "google_secret_manager_secret" "dev" {
  for_each = local.secret_values

  project   = var.project_id
  secret_id = each.key

  replication {
    auto {}
  }

  depends_on = [google_project_service.apis]
}

resource "google_secret_manager_secret_version" "dev" {
  for_each = local.secret_values

  secret      = google_secret_manager_secret.dev[each.key].id
  secret_data = each.value
}

# The four k8s objects `deploy/k8s/*.yaml` already reference by name — this
# is `deploy/k8s/secrets.example.yaml`, filled in. The ClusterIssuer is
# deliberately NOT here; see docs/infra-dev-plan.md §2.
resource "kubernetes_secret" "db" {
  metadata {
    name      = "medstock-db"
    namespace = "medstock"
  }
  data = {
    url = local.database_url
  }

  depends_on = [google_container_node_pool.spot, kubernetes_namespace.medstock]
}

resource "kubernetes_secret" "auth" {
  metadata {
    name      = "medstock-auth"
    namespace = "medstock"
  }
  data = {
    jwt-private-key = tls_private_key.jwt.private_key_pem
  }

  depends_on = [google_container_node_pool.spot, kubernetes_namespace.medstock]
}

resource "kubernetes_secret" "ai" {
  metadata {
    name      = "medstock-ai"
    namespace = "medstock"
  }
  data = {
    gemini-api-key = var.gemini_api_key
  }

  depends_on = [google_container_node_pool.spot, kubernetes_namespace.medstock]
}

resource "kubernetes_config_map" "jwt" {
  metadata {
    name      = "medstock-jwt"
    namespace = "medstock"
  }
  data = {
    public-key = tls_private_key.jwt.public_key_pem
  }

  depends_on = [google_container_node_pool.spot, kubernetes_namespace.medstock]
}

# `deploy/k8s/namespace.yaml` creates this too, but the overlay applies after
# these Secrets — kustomize's `kubectl apply -k` is fine re-applying a
# Namespace that already exists, so create it here rather than block the k8s
# provider on a manifest that hasn't been applied yet.
resource "kubernetes_namespace" "medstock" {
  metadata {
    name = "medstock"
  }

  depends_on = [google_container_node_pool.spot]
}
