variable "project_id" {
  description = "GCP project to deploy into. No default — this must never accidentally target the wrong project."
  type        = string
}

variable "region" {
  description = "GKE free-tier zonal cluster credit applies in any region. europe-west1 (Belgium): cheapest EU region, well-stocked for e2-medium Spot — switched from us-central1 after that region ran out of Spot capacity."
  type        = string
  default     = "europe-west1"
}

variable "zone" {
  type    = string
  default = "europe-west1-b"
}

variable "gemini_api_key" {
  description = "Cannot be generated by Terraform. Pass via TF_VAR_gemini_api_key, never a committed tfvars."
  type        = string
  sensitive   = true
}

variable "dev_members" {
  description = "Emails of teammates granted container.developer, cloudsql.client and secretmanager.secretAccessor."
  type        = list(string)
  default     = []
}

variable "github_repo" {
  description = "owner/repo — the only repo whose GitHub Actions runs may impersonate the CI service account (ci.tf)."
  type        = string
}

variable "letsencrypt_email" {
  description = "Used by the ClusterIssuer in deploy/overlays/dev/cluster-issuer.yaml, not by any Terraform resource — surfaced as an output so the README's replace step has one source of truth."
  type        = string
}
