variable "project_id" {
  description = "GCP project to deploy into. No default — this must never accidentally target the wrong project."
  type        = string
}

variable "region" {
  description = "Cheapest region with the GKE free-tier zonal cluster credit."
  type        = string
  default     = "us-central1"
}

variable "zone" {
  type    = string
  default = "us-central1-a"
}

variable "gemini_api_key" {
  description = "Cannot be generated by Terraform. Pass via TF_VAR_gemini_api_key, never a committed tfvars."
  type        = string
  sensitive   = true
}

variable "dev_members" {
  description = "Emails of teammates granted container.developer, cloudsql.client and secretmanager.secretAccessor."
  type        = list(string)
  default     = []
}

variable "letsencrypt_email" {
  description = "Used by the ClusterIssuer in deploy/k8s/overlays/dev/cluster-issuer.yaml, not by any Terraform resource — surfaced as an output so the README's replace step has one source of truth."
  type        = string
}
