"""Patient-profiling rules — PP-1/PP-2, docs/patient-pipeline.md.

Deterministic. No model on this path: the same vector and candidate always give
the same verdict, with the same reasons, so a pharmacist can argue with it and a
regulator can reproduce it.

**No PHI.** Everything here operates on a de-identified feature vector
(docs/patient-profiling-usecases.md §2.3) — age band, organ-function band, coded
allergies and conditions, current RxCUIs. There is no name, no identifier, no
date. A `patient_ref` may be carried through, but it is opaque and generated by
the hospital; we never hold the mapping.

The reference tables at the bottom are a deliberately small, hand-checked seed
so the pipeline is exercisable end to end. Real deployments replace them with the
offline-built tables in docs/patient-pipeline.md §5 — the rule code does not
change when they do.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Sequence
from dataclasses import dataclass, field, replace
from datetime import UTC, date, datetime
from enum import StrEnum
from typing import Any

RULESET_VERSION = "2026.08.1"


class Severity(StrEnum):
    BLOCK = "block"
    HIGH = "high"
    MODERATE = "moderate"
    LOW = "low"
    INFO = "info"


class Verdict(StrEnum):
    BLOCKED = "blocked"
    RED = "red"
    AMBER = "amber"
    GREEN = "green"


# The clinical opinion of the product, in one place so a pharmacist can review it
# as a unit rather than hunting through nine stages. Changing a number here is a
# ruleset change, not a code change.
WEIGHTS: dict[str, int] = {
    "PRIOR_ADR_SAME_CLASS": 45,
    "INTERACTION_MAJOR": 40,
    "RENAL_DOSE_EXCEEDED": 30,
    "DUPLICATE_CLASS": 25,
    "HEPATIC_IMPAIRED": 20,
    "AGE_INAPPROPRIATE": 20,
    "INTERACTION_MODERATE": 15,
    "NARROW_THERAPEUTIC_INDEX": 10,
}
BANDS: tuple[tuple[int, Verdict], ...] = ((0, Verdict.GREEN), (30, Verdict.AMBER), (60, Verdict.RED))


@dataclass(frozen=True)
class Finding:
    code: str
    severity: Severity
    weight: int
    message: str
    source: str
    stage: int


@dataclass(frozen=True)
class PatientVector:
    """De-identified. `patient_ref` is opaque and hospital-generated; we hold no
    mapping back to a person (docs/phi-readiness.md §5)."""

    age_band: str = "unknown"  # "18-39" | "40-64" | "65-74" | "75-89" | "90+"
    sex: str = "unknown"
    egfr_band: str = "unknown"  # ">=90" | "60-89" | "45-59" | "30-44" | "15-29" | "<15"
    hepatic: str = "unknown"  # "normal" | "impaired" | "unknown"
    allergy_codes: tuple[str, ...] = ()
    condition_codes: tuple[str, ...] = ()
    active_rxcuis: tuple[str, ...] = ()
    prior_adr_rxcuis: tuple[str, ...] = ()
    patient_ref: str | None = None

    @classmethod
    def from_json(cls, payload: dict) -> PatientVector:
        """Accept a third-party payload. Unknown keys are ignored rather than
        stored — that rejection is what keeps a hospital from accidentally
        sending us a name (docs/phi-readiness.md §4)."""
        def tup(key: str) -> tuple[str, ...]:
            value = payload.get(key) or []
            return tuple(str(v) for v in value) if isinstance(value, (list, tuple)) else ()

        return cls(
            age_band=str(payload.get("age_band") or "unknown"),
            sex=str(payload.get("sex") or "unknown"),
            egfr_band=str(payload.get("egfr_band") or "unknown"),
            hepatic=str(payload.get("hepatic") or "unknown"),
            allergy_codes=tup("allergy_codes"),
            condition_codes=tup("condition_codes"),
            active_rxcuis=tup("active_rxcuis"),
            prior_adr_rxcuis=tup("prior_adr_rxcuis"),
            patient_ref=(str(payload["patient_ref"]) if payload.get("patient_ref") else None),
        )

    def feature_hash(self) -> str:
        """Stable fingerprint of the question, for `assessment_log`.

        **`patient_ref` is excluded, and that exclusion is the point.** It is
        opaque to us but stable per patient, so including it would let anyone
        holding the audit table group every assessment ever made about one
        person — building a re-identification handle out of the audit trail the
        no-PHI design depends on (docs/patient-profiling-usecases.md §2.4).

        Sequence fields are sorted before hashing: the same allergies in a
        different order are the same question, and a hash that disagreed would
        make the log unable to recognise a repeat.
        """
        payload = json.dumps(
            {
                "age_band": self.age_band,
                "sex": self.sex,
                "egfr_band": self.egfr_band,
                "hepatic": self.hepatic,
                "allergy_codes": sorted(self.allergy_codes),
                "condition_codes": sorted(self.condition_codes),
                "active_rxcuis": sorted(self.active_rxcuis),
                "prior_adr_rxcuis": sorted(self.prior_adr_rxcuis),
            },
            sort_keys=True,
            separators=(",", ":"),
        )
        return hashlib.sha256(payload.encode()).hexdigest()


@dataclass(frozen=True)
class Assessment:
    verdict: Verdict
    score: int | None  # None when blocked — no number is produced for a hard gate
    findings: tuple[Finding, ...]
    stages_completed: tuple[int, ...]
    rxcui: str
    ruleset_version: str = RULESET_VERSION

    def as_dict(self) -> dict:
        return {
            "rxcui": self.rxcui,
            "verdict": str(self.verdict),
            "score": self.score,
            "ruleset_version": self.ruleset_version,
            "stages_completed": list(self.stages_completed),
            "findings": [
                {
                    "code": f.code,
                    "severity": str(f.severity),
                    "weight": f.weight,
                    "message": f.message,
                    "source": f.source,
                    "stage": f.stage,
                }
                for f in self.findings
            ],
        }


# --- reference tables (seed) -------------------------------------------------
# Small and hand-checked. docs/patient-pipeline.md §5 describes the CronJobs that
# build the real ones from CPIC, label text and FAERS.

DRUG_CLASS: dict[str, str] = {
    "308182": "penicillin",  # amoxicillin
    "723": "penicillin",  # ampicillin
    "617310": "statin",  # atorvastatin
    "36567": "statin",  # simvastatin
    "314076": "ace_inhibitor",  # lisinopril
    "29046": "ace_inhibitor",  # enalapril
    "200801": "loop_diuretic",  # furosemide
    "246461": "nsaid",  # aspirin
    "197603": "nsaid",  # diflunisal
    "198479": "nsaid",  # aspirin/caffeine
    "5640": "nsaid",  # ibuprofen
    "861007": "biguanide",  # metformin
    "312086": "antiemetic",  # ondansetron
    "311700": "benzodiazepine",  # midazolam
    "11289": "anticoagulant",  # warfarin
}

ALLERGY_CLASS: dict[str, str] = {
    "penicillin": "penicillin",
    "amoxicillin": "penicillin",
    "sulfa": "sulfonamide",
    "nsaid": "nsaid",
    "aspirin": "nsaid",
    "ace_inhibitor": "ace_inhibitor",
    # Ingredient-level demo codes (not drug-class allergies) — handled by
    # avoided_ingredient_warnings(), not ALLERGY_MATCH class gates.
    "caffeine": "ingredient:caffeine",
}

# Profile codes (allergy or condition) → RxNorm ingredient RxCUI to avoid.
# Used by the physician cart-check path (warnings only).
AVOID_INGREDIENT_CODES: dict[str, tuple[str, str]] = {
    "caffeine": ("1886", "caffeine"),
    "avoid_caffeine": ("1886", "caffeine"),
}

# (class_a, class_b) -> severity code
INTERACTIONS: dict[frozenset[str], str] = {
    frozenset({"anticoagulant", "nsaid"}): "INTERACTION_MAJOR",
    frozenset({"anticoagulant", "statin"}): "INTERACTION_MODERATE",
    frozenset({"ace_inhibitor", "loop_diuretic"}): "INTERACTION_MODERATE",
    frozenset({"ace_inhibitor", "nsaid"}): "INTERACTION_MAJOR",
    frozenset({"benzodiazepine", "antiemetic"}): "INTERACTION_MODERATE",
}

# Minimum eGFR band index a drug tolerates. Bands are ordered worst -> best.
EGFR_ORDER = ("<15", "15-29", "30-44", "45-59", "60-89", ">=90")
RENAL_MIN_BAND: dict[str, str] = {
    "biguanide": "30-44",  # metformin: avoid below 30
    "nsaid": "30-44",
    "ace_inhibitor": "15-29",
    "loop_diuretic": "15-29",
}

HEPATIC_RISK = {"statin", "benzodiazepine"}
NARROW_THERAPEUTIC_INDEX = {"anticoagulant"}
# Classes with published caution in older adults (Beers-style seed).
AGE_INAPPROPRIATE = {"benzodiazepine", "nsaid"}
OLDER_BANDS = {"75-89", "90+"}


# --- PP-3 prognosis ----------------------------------------------------------
# Ordered worst -> best, so "at_or_below" on kidney function means "this band or
# worse" the way a clinician means it.
AGE_ORDER = ("18-39", "40-64", "65-74", "75-89", "90+")
_ORDERED: dict[str, tuple[str, ...]] = {"egfr_band": EGFR_ORDER, "age_band": AGE_ORDER}

# A reaction the label calls fatal, with every stated risk factor present, is
# worth more than a moderate one with half of them. Scaled by the fraction
# matched, so partial evidence scores partially.
PROGNOSIS_BASE = {"fatal": 40, "serious": 25, "moderate": 12}


@dataclass(frozen=True)
class RiskProfile:
    """One approved row of `drug_risk_profile`. Extracted by a model from label
    prose, checked against a closed vocabulary, approved by a pharmacist — and
    applied here by arithmetic (docs/prognosis-and-procurement.md §1.4)."""

    rxcui: str
    reaction: str
    seriousness: str
    risk_factors: tuple[dict, ...]
    citation: str = ""
    section: str = ""


def _factor_matches(vector: PatientVector, factor: dict) -> str | None:
    """The patient's value if this risk factor applies, else `None`.

    Returns the value rather than a bool so the finding can say *which*
    characteristics matched — "eGFR 30-44, age 75-89" is reviewable, "3 factors"
    is not.
    """
    feature, op, value = factor.get("feature"), factor.get("op"), factor.get("value")
    actual = getattr(vector, feature, None)
    if actual in (None, "unknown", ()):
        return None  # unknown never counts as a match; it is reported separately

    if op == "eq":
        return str(actual) if actual == value else None

    if op == "in":
        allowed = [str(v) for v in (value if isinstance(value, list) else [value])]
        if isinstance(actual, tuple):
            # A collection field: "in" means any of these codes is present. The
            # scalar reading (`actual in allowed`) can never be true for a tuple,
            # so a real extraction like "renal artery stenosis, CKD, heart
            # failure" would have silently matched nobody.
            hit = [code for code in actual if str(code) in allowed]
            return ", ".join(hit) if hit else None
        return str(actual) if str(actual) in allowed else None

    if op == "has":
        # Collection fields: allergy_codes, condition_codes, active_rxcuis, …
        return str(value) if isinstance(actual, tuple) and str(value) in actual else None

    order = _ORDERED.get(feature)
    if order is None or actual not in order or value not in order:
        return None
    if op == "at_or_below":
        return str(actual) if order.index(actual) <= order.index(value) else None
    if op == "at_or_above":
        return str(actual) if order.index(actual) >= order.index(value) else None
    return None


def prognosis_findings(
    vector: PatientVector, profiles: Sequence[RiskProfile]
) -> list[Finding]:
    """Label-derived risk that applies to *this* patient.

    Raises a score; never blocks. A hard gate is an absolute, and a model must
    not be able to create or clear one — see §1.5 of the design.
    """
    findings: list[Finding] = []
    for profile in profiles:
        factors = list(profile.risk_factors)
        if not factors:
            continue
        matched = [m for f in factors if (m := _factor_matches(vector, f)) is not None]
        if not matched:
            continue

        base = PROGNOSIS_BASE.get(profile.seriousness.lower(), PROGNOSIS_BASE["moderate"])
        weight = round(base * len(matched) / len(factors))
        findings.append(
            Finding(
                code="PROGNOSIS_RISK",
                severity=Severity.HIGH if weight >= 25 else Severity.MODERATE,
                weight=weight,
                message=(
                    f"{len(matched)} of {len(factors)} label risk factors present for "
                    f"{profile.reaction} ({', '.join(matched)})"
                ),
                source=f"FDA label, {profile.section or 'unspecified section'}",
                stage=7,
            )
        )
    return findings


def _class_of(rxcui: str) -> str | None:
    return DRUG_CLASS.get(str(rxcui))


def _band_index(band: str) -> int | None:
    return EGFR_ORDER.index(band) if band in EGFR_ORDER else None


def age_band_from_dob(dob: date, today: date | None = None) -> str:
    """Map calendar age to the PatientVector age_band vocabulary."""
    today = today or datetime.now(tz=UTC).date()
    years = today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day))
    if years < 18:
        return "18-39"  # pediatric bands not modeled; nearest adult band
    if years < 40:
        return "18-39"
    if years < 65:
        return "40-64"
    if years < 75:
        return "65-74"
    if years < 90:
        return "75-89"
    return "90+"


def patient_row_to_vector(row: Any, active_rxcuis: Sequence[str] = ()) -> PatientVector:
    """Strip PHI from a Patient ORM row into the de-identified rules vector.

    Demo exception: the DB row may hold name/DOB; the vector never does.
    """
    allergies = tuple(str(a) for a in (getattr(row, "allergy_codes", None) or ()))
    conditions = tuple(str(c) for c in (getattr(row, "condition_codes", None) or ()))
    dob = getattr(row, "date_of_birth", None)
    return PatientVector(
        age_band=age_band_from_dob(dob) if isinstance(dob, date) else "unknown",
        allergy_codes=allergies,
        condition_codes=conditions,
        active_rxcuis=tuple(str(r) for r in active_rxcuis),
        patient_ref=str(row.id) if getattr(row, "id", None) else None,
    )


def profile_avoided_ingredients(vector: PatientVector) -> list[tuple[str, str, str]]:
    """Return (profile_code, ingredient_rxcui, ingredient_name) from allergies+conditions."""
    out: list[tuple[str, str, str]] = []
    seen: set[str] = set()
    for code in (*vector.allergy_codes, *vector.condition_codes):
        key = code.lower().strip()
        mapped = AVOID_INGREDIENT_CODES.get(key)
        if not mapped:
            continue
        ing_rxcui, ing_name = mapped
        if ing_rxcui in seen:
            continue
        seen.add(ing_rxcui)
        out.append((key, ing_rxcui, ing_name))
    return out


def avoided_ingredient_warnings(
    vector: PatientVector,
    rxcui: str,
    ingredients: Sequence[dict[str, str]],
) -> list[Finding]:
    """Warnings when the drug's RxNorm ingredients intersect profile avoid-codes.

    Severity is always LOW (warning only) — cart UI never hard-blocks on this.
    """
    findings: list[Finding] = []
    ing_by_id = {str(i["rxcui"]): str(i.get("name") or i["rxcui"]) for i in ingredients}
    for profile_code, ing_rxcui, ing_name in profile_avoided_ingredients(vector):
        if ing_rxcui not in ing_by_id:
            # Also match by name substring when RxCUI resolution used a synonym.
            hay = " ".join(ing_by_id.values()).lower()
            if ing_name.lower() not in hay:
                continue
        findings.append(
            Finding(
                "AVOIDED_INGREDIENT",
                Severity.LOW,
                0,
                f"Patient profile flags '{profile_code}' — this drug contains {ing_name}",
                "profile + RxNorm ingredient",
                4,
            )
        )
    return findings


def assess(
    vector: PatientVector,
    rxcui: str,
    today=None,
    risk_profiles: Sequence[RiskProfile] = (),
) -> Assessment:
    """Run the deterministic stages for one candidate drug.

    Stage 4 short-circuits: a hard gate ends the pipeline and **no score is
    computed**, because a number beside an absolute contraindication invites
    someone to weigh it against a discount.
    """
    findings: list[Finding] = []
    stages: list[int] = [1, 2, 3]
    candidate_class = _class_of(rxcui)

    if candidate_class is None:
        findings.append(
            Finding("DRUG_CLASS_UNKNOWN", Severity.INFO, 0,
                    f"No class mapping for RxCUI {rxcui}; class rules skipped",
                    "reference seed", 3)
        )

    # --- stage 4: hard gates ------------------------------------------------
    stages.append(4)
    blocks: list[Finding] = []
    for allergy in vector.allergy_codes:
        allergy_class = ALLERGY_CLASS.get(allergy.lower(), allergy.lower())
        if candidate_class and allergy_class == candidate_class:
            blocks.append(
                Finding("ALLERGY_MATCH", Severity.BLOCK, 0,
                        f"Patient is allergic to {allergy} — same class as this drug "
                        f"({candidate_class})", "allergy list", 4)
            )
    if str(rxcui) in vector.active_rxcuis:
        blocks.append(
            Finding("DUPLICATE_INGREDIENT", Severity.BLOCK, 0,
                    "Patient is already taking this exact drug", "current regimen", 4)
        )
    if blocks:
        return Assessment(Verdict.BLOCKED, None, tuple(findings + blocks), tuple(stages), str(rxcui))

    # --- stage 5: interactions ---------------------------------------------
    stages.append(5)
    for other in vector.active_rxcuis:
        other_class = _class_of(other)
        if not candidate_class or not other_class or other_class == candidate_class:
            if candidate_class and other_class == candidate_class:
                findings.append(
                    Finding("DUPLICATE_CLASS", Severity.MODERATE, WEIGHTS["DUPLICATE_CLASS"],
                            f"Already on another {candidate_class}", "current regimen", 5)
                )
            continue
        code = INTERACTIONS.get(frozenset({candidate_class, other_class}))
        if code:
            findings.append(
                Finding(code,
                        Severity.HIGH if code.endswith("MAJOR") else Severity.MODERATE,
                        WEIGHTS[code],
                        f"{candidate_class} + {other_class} interaction",
                        "interaction seed", 5)
            )

    # --- stage 6: organ function -------------------------------------------
    stages.append(6)
    limit = RENAL_MIN_BAND.get(candidate_class or "")
    if limit:
        patient_idx, limit_idx = _band_index(vector.egfr_band), _band_index(limit)
        if patient_idx is None:
            findings.append(
                Finding("RENAL_UNKNOWN", Severity.INFO, 0,
                        "Kidney function not supplied — renal limit not checked",
                        "feature vector", 6)
            )
        elif patient_idx < limit_idx:
            findings.append(
                Finding("RENAL_DOSE_EXCEEDED", Severity.HIGH, WEIGHTS["RENAL_DOSE_EXCEEDED"],
                        f"eGFR {vector.egfr_band} is below the {limit} floor for "
                        f"{candidate_class}", "renal seed", 6)
            )
    if candidate_class in HEPATIC_RISK:
        if vector.hepatic == "impaired":
            findings.append(
                Finding("HEPATIC_IMPAIRED", Severity.MODERATE, WEIGHTS["HEPATIC_IMPAIRED"],
                        f"Hepatic impairment with a hepatically cleared {candidate_class}",
                        "hepatic seed", 6)
            )
        elif vector.hepatic == "unknown":
            findings.append(
                Finding("HEPATIC_UNKNOWN", Severity.INFO, 0,
                        "Liver function not supplied — hepatic check skipped",
                        "feature vector", 6)
            )

    # --- stage 7: label-derived prognosis (PP-3) ----------------------------
    # Only profiles for this drug, and only ones a pharmacist has approved —
    # the caller is responsible for that filter, but guard it here too, because
    # an unapproved profile reaching a screen is the one failure this design
    # cannot tolerate.
    applicable = [p for p in risk_profiles if str(p.rxcui) == str(rxcui)]
    if applicable:
        stages.append(7)
        findings.extend(prognosis_findings(vector, applicable))

    # --- stage 8 (pharmacogenomics) is an offline table; not seeded here ----

    # --- stage 9: age ------------------------------------------------------
    stages.append(9)
    if vector.age_band in OLDER_BANDS and candidate_class in AGE_INAPPROPRIATE:
        findings.append(
            Finding("AGE_INAPPROPRIATE", Severity.MODERATE, WEIGHTS["AGE_INAPPROPRIATE"],
                    f"{candidate_class} carries published caution at age {vector.age_band}",
                    "age seed", 9)
        )

    # prior ADR to the same class
    for prior in vector.prior_adr_rxcuis:
        if candidate_class and _class_of(prior) == candidate_class:
            findings.append(
                Finding("PRIOR_ADR_SAME_CLASS", Severity.HIGH, WEIGHTS["PRIOR_ADR_SAME_CLASS"],
                        f"Previous adverse reaction to another {candidate_class}",
                        "prior ADR history", 9)
            )
    if candidate_class in NARROW_THERAPEUTIC_INDEX:
        findings.append(
            Finding("NARROW_THERAPEUTIC_INDEX", Severity.LOW,
                    WEIGHTS["NARROW_THERAPEUTIC_INDEX"],
                    f"{candidate_class} has a narrow therapeutic index", "reference seed", 9)
        )

    # --- stage 10: aggregate ----------------------------------------------
    stages.append(10)
    score = sum(f.weight for f in findings)
    verdict = next(v for threshold, v in reversed(BANDS) if score >= threshold)
    return Assessment(verdict, score, tuple(findings), tuple(stages), str(rxcui))


# --- mass purchasing ---------------------------------------------------------


@dataclass
class DemandLine:
    rxcui: str
    on_therapy: int = 0  # patients already taking it
    substitutes_for: int = 0  # patients routed here off a withdrawn drug
    eligible: int = 0  # could safely take it, whether or not they need it
    blocked: int = 0
    flagged: int = 0  # amber/red — usable but wants review
    units_needed: int = 0
    on_hand: int = 0
    reasons: dict[str, int] = field(default_factory=dict)
    # PP-4. at_risk counts only patients *on* the drug whose own profile flags
    # it — a subset of on_therapy, unlike `flagged` which spans the whole
    # cohort including people who will never take it. Conflating the two
    # inflates the projection with patients who are not there to leave.
    at_risk: int = 0
    switch_in: int = 0  # expected arrivals from a drug they are at risk on

    @property
    def shortfall(self) -> int:
        return max(0, self.units_needed - self.on_hand)

    def cohort_fit(self, cohort_size: int) -> float:
        """Share of the whole cohort who could ever take this.

        A drug most of the cohort cannot take is a bad stocking bet even when
        current usage looks healthy (docs/prognosis-and-procurement.md §2.3).
        """
        if cohort_size <= 0:
            return 0.0
        return round(self.eligible / cohort_size, 4)

    def projected(self, switch_rate: float) -> int:
        """projected = on_therapy − (at_risk × switch_rate) + switch_in

        Rounded to whole patients, and never below zero: switch_rate is an
        assumption, and an assumption must not be able to produce a negative
        headcount and have it read as a real number downstream.
        """
        moved = self.at_risk * switch_rate
        return max(0, round(self.on_therapy - moved + self.switch_in))


def assess_current_therapy(
    patient: PatientVector,
    rxcui: str,
    risk_profiles: Sequence[RiskProfile] = (),
) -> Assessment:
    """Risk of a drug the patient is **already taking**.

    `assess` answers a different question: *should we start this patient on this
    drug*. Asked about current therapy it blocks every time on
    DUPLICATE_INGREDIENT -- the patient is, correctly, already on it. Used as a
    risk signal that reads as "100% of patients are at risk", which is not a
    finding, it is the question being asked wrong.

    So the drug is removed from the active list and the patient re-assessed as
    if considering it fresh. Everything that makes current therapy risky still
    fires -- renal floor, age, prior ADR, PP-3 label profiles, interactions with
    the *rest* of the regimen -- while the tautology does not. Interactions are
    unaffected by the removal because a drug cannot interact with itself.
    """
    others = tuple(r for r in patient.active_rxcuis if str(r) != str(rxcui))
    as_if_new = replace(patient, active_rxcuis=others)
    return assess(as_if_new, rxcui, risk_profiles=risk_profiles)


def best_substitute(
    patient: PatientVector,
    withdrawn: str,
    candidates: Sequence[str],
    unavailable: set[str],
    risk_profiles: Sequence[RiskProfile] = (),
) -> tuple[str | None, str]:
    """The safest in-class replacement for one patient, or a reason there is none.

    Substitution stays **within the therapeutic class**. A drug being safe is not
    a reason to prescribe it — a patient on an ACE inhibitor for hypertension is
    not helped by an antiemetic just because nothing blocks it.
    """
    target_class = _class_of(withdrawn)
    if target_class is None:
        return None, "no class mapping for the withdrawn drug"

    best: tuple[int, str] | None = None
    for rxcui in candidates:
        rxcui = str(rxcui)
        if rxcui == str(withdrawn) or rxcui in unavailable:
            continue
        if _class_of(rxcui) != target_class:
            continue
        result = assess(patient, rxcui, risk_profiles=risk_profiles)
        if result.verdict is Verdict.BLOCKED:
            continue
        score = result.score or 0
        if best is None or score < best[0]:
            best = (score, rxcui)
    if best is None:
        return None, f"no available, tolerated {target_class} alternative"
    return best[1], ""


def plan_demand(
    cohort: Sequence[PatientVector],
    candidates: Sequence[str],
    on_hand: dict[str, int] | None = None,
    unavailable: Sequence[str] = (),
    units_per_patient: int = 30,
    risk_profiles: Sequence[RiskProfile] = (),
) -> tuple[dict[str, DemandLine], dict[str, int]]:
    """Aggregate a cohort into a purchasing plan.

    **Demand follows therapy, not eligibility.** A patient generates demand for
    the drugs they are actually on; the fact that they *could* tolerate six
    others is a safety statistic, not a reason to buy six others. Planning off
    eligibility puts the whole cohort on whichever safe drug happens to sort
    first, which is how this function behaved before and it was wrong.

    `unavailable` is the bridge from COMP-1: a drug that is red or in shortage
    is withdrawn, and each affected patient is re-routed to the safest **in-class**
    alternative for them individually. Patients with no such alternative are
    counted, not silently dropped — that count is the number a director needs.

    Returns the per-drug lines and a summary of what could not be served.
    """
    on_hand = on_hand or {}
    unavailable_set = {str(u) for u in unavailable}
    known = [str(r) for r in candidates]
    lines = {r: DemandLine(rxcui=r, on_hand=on_hand.get(r, 0)) for r in known}
    unserved: dict[str, int] = {}

    for patient in cohort:
        # Safety statistics across every candidate — useful to a pharmacist even
        # where it does not drive a purchase.
        for rxcui in known:
            result = assess(patient, rxcui, risk_profiles=risk_profiles)
            line = lines[rxcui]
            if result.verdict is Verdict.BLOCKED:
                line.blocked += 1
                for f in result.findings:
                    if f.severity is Severity.BLOCK:
                        line.reasons[f.code] = line.reasons.get(f.code, 0) + 1
                continue
            line.eligible += 1
            if result.verdict is not Verdict.GREEN:
                line.flagged += 1

        # Demand: only for therapy this patient is actually on.
        for rxcui in patient.active_rxcuis:
            rxcui = str(rxcui)
            if rxcui not in lines:
                continue  # not a drug we are planning to stock
            if rxcui not in unavailable_set:
                lines[rxcui].on_therapy += 1
                lines[rxcui].units_needed += units_per_patient
                # PP-4: is this patient, on this drug, flagged by their own
                # profile? Assessed as current therapy rather than as a new
                # prescription -- see assess_current_therapy for why the plain
                # call would count every patient as at risk.
                on_therapy_result = assess_current_therapy(
                    patient, rxcui, risk_profiles=risk_profiles
                )
                if on_therapy_result.verdict is not Verdict.GREEN:
                    lines[rxcui].at_risk += 1
                    # Where they would go if switched. Counted as pressure on
                    # the alternative now, so a re-order decision is visible
                    # this quarter rather than a surprise next.
                    destination, _ = best_substitute(
                        patient, rxcui, known, unavailable_set, risk_profiles=risk_profiles
                    )
                    if destination is not None:
                        lines[destination].switch_in += 1
                continue
            alternative, reason = best_substitute(
                patient, rxcui, known, unavailable_set, risk_profiles=risk_profiles
            )
            if alternative is None:
                unserved[reason] = unserved.get(reason, 0) + 1
                continue
            lines[alternative].substitutes_for += 1
            lines[alternative].units_needed += units_per_patient

    return lines, unserved
