"""Patient-profiling rules — PP-1/PP-2, docs/patient-pipeline.md.

Deterministic. No model on this path: the same vector and candidate always give
the same verdict, with the same reasons, so a pharmacist can argue with it and a
regulator can reproduce it.

**No PHI.** Everything here operates on a de-identified feature vector
(docs/patient-profiling-usecases.md §2.3) — age band, organ-function band, coded
allergies and conditions, current RxCUIs. There is no name, no identifier, no
date. A `patient_ref` may be carried through, but it is opaque and generated by
the hospital; we never hold the mapping.

The reference tables at the bottom are a deliberately small, hand-checked seed
so the pipeline is exercisable end to end. Real deployments replace them with the
offline-built tables in docs/patient-pipeline.md §5 — the rule code does not
change when they do.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass, field
from enum import StrEnum

RULESET_VERSION = "2026.08.1"


class Severity(StrEnum):
    BLOCK = "block"
    HIGH = "high"
    MODERATE = "moderate"
    LOW = "low"
    INFO = "info"


class Verdict(StrEnum):
    BLOCKED = "blocked"
    RED = "red"
    AMBER = "amber"
    GREEN = "green"


# The clinical opinion of the product, in one place so a pharmacist can review it
# as a unit rather than hunting through nine stages. Changing a number here is a
# ruleset change, not a code change.
WEIGHTS: dict[str, int] = {
    "PRIOR_ADR_SAME_CLASS": 45,
    "INTERACTION_MAJOR": 40,
    "RENAL_DOSE_EXCEEDED": 30,
    "DUPLICATE_CLASS": 25,
    "HEPATIC_IMPAIRED": 20,
    "AGE_INAPPROPRIATE": 20,
    "INTERACTION_MODERATE": 15,
    "NARROW_THERAPEUTIC_INDEX": 10,
}
BANDS: tuple[tuple[int, Verdict], ...] = ((0, Verdict.GREEN), (30, Verdict.AMBER), (60, Verdict.RED))


@dataclass(frozen=True)
class Finding:
    code: str
    severity: Severity
    weight: int
    message: str
    source: str
    stage: int


@dataclass(frozen=True)
class PatientVector:
    """De-identified. `patient_ref` is opaque and hospital-generated; we hold no
    mapping back to a person (docs/phi-readiness.md §5)."""

    age_band: str = "unknown"  # "18-39" | "40-64" | "65-74" | "75-89" | "90+"
    sex: str = "unknown"
    egfr_band: str = "unknown"  # ">=90" | "60-89" | "45-59" | "30-44" | "15-29" | "<15"
    hepatic: str = "unknown"  # "normal" | "impaired" | "unknown"
    allergy_codes: tuple[str, ...] = ()
    condition_codes: tuple[str, ...] = ()
    active_rxcuis: tuple[str, ...] = ()
    prior_adr_rxcuis: tuple[str, ...] = ()
    patient_ref: str | None = None

    @classmethod
    def from_json(cls, payload: dict) -> PatientVector:
        """Accept a third-party payload. Unknown keys are ignored rather than
        stored — that rejection is what keeps a hospital from accidentally
        sending us a name (docs/phi-readiness.md §4)."""
        def tup(key: str) -> tuple[str, ...]:
            value = payload.get(key) or []
            return tuple(str(v) for v in value) if isinstance(value, (list, tuple)) else ()

        return cls(
            age_band=str(payload.get("age_band") or "unknown"),
            sex=str(payload.get("sex") or "unknown"),
            egfr_band=str(payload.get("egfr_band") or "unknown"),
            hepatic=str(payload.get("hepatic") or "unknown"),
            allergy_codes=tup("allergy_codes"),
            condition_codes=tup("condition_codes"),
            active_rxcuis=tup("active_rxcuis"),
            prior_adr_rxcuis=tup("prior_adr_rxcuis"),
            patient_ref=(str(payload["patient_ref"]) if payload.get("patient_ref") else None),
        )


@dataclass(frozen=True)
class Assessment:
    verdict: Verdict
    score: int | None  # None when blocked — no number is produced for a hard gate
    findings: tuple[Finding, ...]
    stages_completed: tuple[int, ...]
    rxcui: str
    ruleset_version: str = RULESET_VERSION

    def as_dict(self) -> dict:
        return {
            "rxcui": self.rxcui,
            "verdict": str(self.verdict),
            "score": self.score,
            "ruleset_version": self.ruleset_version,
            "stages_completed": list(self.stages_completed),
            "findings": [
                {
                    "code": f.code,
                    "severity": str(f.severity),
                    "weight": f.weight,
                    "message": f.message,
                    "source": f.source,
                    "stage": f.stage,
                }
                for f in self.findings
            ],
        }


# --- reference tables (seed) -------------------------------------------------
# Small and hand-checked. docs/patient-pipeline.md §5 describes the CronJobs that
# build the real ones from CPIC, label text and FAERS.

DRUG_CLASS: dict[str, str] = {
    "308182": "penicillin",  # amoxicillin
    "723": "penicillin",  # ampicillin
    "617310": "statin",  # atorvastatin
    "36567": "statin",  # simvastatin
    "314076": "ace_inhibitor",  # lisinopril
    "29046": "ace_inhibitor",  # enalapril
    "200801": "loop_diuretic",  # furosemide
    "246461": "nsaid",  # aspirin
    "197603": "nsaid",  # diflunisal
    "198479": "nsaid",  # aspirin/caffeine
    "5640": "nsaid",  # ibuprofen
    "861007": "biguanide",  # metformin
    "312086": "antiemetic",  # ondansetron
    "311700": "benzodiazepine",  # midazolam
    "11289": "anticoagulant",  # warfarin
}

ALLERGY_CLASS: dict[str, str] = {
    "penicillin": "penicillin",
    "amoxicillin": "penicillin",
    "sulfa": "sulfonamide",
    "nsaid": "nsaid",
    "aspirin": "nsaid",
    "ace_inhibitor": "ace_inhibitor",
}

# (class_a, class_b) -> severity code
INTERACTIONS: dict[frozenset[str], str] = {
    frozenset({"anticoagulant", "nsaid"}): "INTERACTION_MAJOR",
    frozenset({"anticoagulant", "statin"}): "INTERACTION_MODERATE",
    frozenset({"ace_inhibitor", "loop_diuretic"}): "INTERACTION_MODERATE",
    frozenset({"ace_inhibitor", "nsaid"}): "INTERACTION_MAJOR",
    frozenset({"benzodiazepine", "antiemetic"}): "INTERACTION_MODERATE",
}

# Minimum eGFR band index a drug tolerates. Bands are ordered worst -> best.
EGFR_ORDER = ("<15", "15-29", "30-44", "45-59", "60-89", ">=90")
RENAL_MIN_BAND: dict[str, str] = {
    "biguanide": "30-44",  # metformin: avoid below 30
    "nsaid": "30-44",
    "ace_inhibitor": "15-29",
    "loop_diuretic": "15-29",
}

HEPATIC_RISK = {"statin", "benzodiazepine"}
NARROW_THERAPEUTIC_INDEX = {"anticoagulant"}
# Classes with published caution in older adults (Beers-style seed).
AGE_INAPPROPRIATE = {"benzodiazepine", "nsaid"}
OLDER_BANDS = {"75-89", "90+"}


def _class_of(rxcui: str) -> str | None:
    return DRUG_CLASS.get(str(rxcui))


def _band_index(band: str) -> int | None:
    return EGFR_ORDER.index(band) if band in EGFR_ORDER else None


def assess(vector: PatientVector, rxcui: str, today=None) -> Assessment:
    """Run the deterministic stages for one candidate drug.

    Stage 4 short-circuits: a hard gate ends the pipeline and **no score is
    computed**, because a number beside an absolute contraindication invites
    someone to weigh it against a discount.
    """
    findings: list[Finding] = []
    stages: list[int] = [1, 2, 3]
    candidate_class = _class_of(rxcui)

    if candidate_class is None:
        findings.append(
            Finding("DRUG_CLASS_UNKNOWN", Severity.INFO, 0,
                    f"No class mapping for RxCUI {rxcui}; class rules skipped",
                    "reference seed", 3)
        )

    # --- stage 4: hard gates ------------------------------------------------
    stages.append(4)
    blocks: list[Finding] = []
    for allergy in vector.allergy_codes:
        allergy_class = ALLERGY_CLASS.get(allergy.lower(), allergy.lower())
        if candidate_class and allergy_class == candidate_class:
            blocks.append(
                Finding("ALLERGY_MATCH", Severity.BLOCK, 0,
                        f"Patient is allergic to {allergy} — same class as this drug "
                        f"({candidate_class})", "allergy list", 4)
            )
    if str(rxcui) in vector.active_rxcuis:
        blocks.append(
            Finding("DUPLICATE_INGREDIENT", Severity.BLOCK, 0,
                    "Patient is already taking this exact drug", "current regimen", 4)
        )
    if blocks:
        return Assessment(Verdict.BLOCKED, None, tuple(findings + blocks), tuple(stages), str(rxcui))

    # --- stage 5: interactions ---------------------------------------------
    stages.append(5)
    for other in vector.active_rxcuis:
        other_class = _class_of(other)
        if not candidate_class or not other_class or other_class == candidate_class:
            if candidate_class and other_class == candidate_class:
                findings.append(
                    Finding("DUPLICATE_CLASS", Severity.MODERATE, WEIGHTS["DUPLICATE_CLASS"],
                            f"Already on another {candidate_class}", "current regimen", 5)
                )
            continue
        code = INTERACTIONS.get(frozenset({candidate_class, other_class}))
        if code:
            findings.append(
                Finding(code,
                        Severity.HIGH if code.endswith("MAJOR") else Severity.MODERATE,
                        WEIGHTS[code],
                        f"{candidate_class} + {other_class} interaction",
                        "interaction seed", 5)
            )

    # --- stage 6: organ function -------------------------------------------
    stages.append(6)
    limit = RENAL_MIN_BAND.get(candidate_class or "")
    if limit:
        patient_idx, limit_idx = _band_index(vector.egfr_band), _band_index(limit)
        if patient_idx is None:
            findings.append(
                Finding("RENAL_UNKNOWN", Severity.INFO, 0,
                        "Kidney function not supplied — renal limit not checked",
                        "feature vector", 6)
            )
        elif patient_idx < limit_idx:
            findings.append(
                Finding("RENAL_DOSE_EXCEEDED", Severity.HIGH, WEIGHTS["RENAL_DOSE_EXCEEDED"],
                        f"eGFR {vector.egfr_band} is below the {limit} floor for "
                        f"{candidate_class}", "renal seed", 6)
            )
    if candidate_class in HEPATIC_RISK:
        if vector.hepatic == "impaired":
            findings.append(
                Finding("HEPATIC_IMPAIRED", Severity.MODERATE, WEIGHTS["HEPATIC_IMPAIRED"],
                        f"Hepatic impairment with a hepatically cleared {candidate_class}",
                        "hepatic seed", 6)
            )
        elif vector.hepatic == "unknown":
            findings.append(
                Finding("HEPATIC_UNKNOWN", Severity.INFO, 0,
                        "Liver function not supplied — hepatic check skipped",
                        "feature vector", 6)
            )

    # --- stage 7/8 are offline tables; not seeded here ----------------------

    # --- stage 9: age ------------------------------------------------------
    stages.append(9)
    if vector.age_band in OLDER_BANDS and candidate_class in AGE_INAPPROPRIATE:
        findings.append(
            Finding("AGE_INAPPROPRIATE", Severity.MODERATE, WEIGHTS["AGE_INAPPROPRIATE"],
                    f"{candidate_class} carries published caution at age {vector.age_band}",
                    "age seed", 9)
        )

    # prior ADR to the same class
    for prior in vector.prior_adr_rxcuis:
        if candidate_class and _class_of(prior) == candidate_class:
            findings.append(
                Finding("PRIOR_ADR_SAME_CLASS", Severity.HIGH, WEIGHTS["PRIOR_ADR_SAME_CLASS"],
                        f"Previous adverse reaction to another {candidate_class}",
                        "prior ADR history", 9)
            )
    if candidate_class in NARROW_THERAPEUTIC_INDEX:
        findings.append(
            Finding("NARROW_THERAPEUTIC_INDEX", Severity.LOW,
                    WEIGHTS["NARROW_THERAPEUTIC_INDEX"],
                    f"{candidate_class} has a narrow therapeutic index", "reference seed", 9)
        )

    # --- stage 10: aggregate ----------------------------------------------
    stages.append(10)
    score = sum(f.weight for f in findings)
    verdict = next(v for threshold, v in reversed(BANDS) if score >= threshold)
    return Assessment(verdict, score, tuple(findings), tuple(stages), str(rxcui))


# --- mass purchasing ---------------------------------------------------------


@dataclass
class DemandLine:
    rxcui: str
    on_therapy: int = 0  # patients already taking it
    substitutes_for: int = 0  # patients routed here off a withdrawn drug
    eligible: int = 0  # could safely take it, whether or not they need it
    blocked: int = 0
    flagged: int = 0  # amber/red — usable but wants review
    units_needed: int = 0
    on_hand: int = 0
    reasons: dict[str, int] = field(default_factory=dict)

    @property
    def shortfall(self) -> int:
        return max(0, self.units_needed - self.on_hand)


def best_substitute(
    patient: PatientVector,
    withdrawn: str,
    candidates: Sequence[str],
    unavailable: set[str],
) -> tuple[str | None, str]:
    """The safest in-class replacement for one patient, or a reason there is none.

    Substitution stays **within the therapeutic class**. A drug being safe is not
    a reason to prescribe it — a patient on an ACE inhibitor for hypertension is
    not helped by an antiemetic just because nothing blocks it.
    """
    target_class = _class_of(withdrawn)
    if target_class is None:
        return None, "no class mapping for the withdrawn drug"

    best: tuple[int, str] | None = None
    for rxcui in candidates:
        rxcui = str(rxcui)
        if rxcui == str(withdrawn) or rxcui in unavailable:
            continue
        if _class_of(rxcui) != target_class:
            continue
        result = assess(patient, rxcui)
        if result.verdict is Verdict.BLOCKED:
            continue
        score = result.score or 0
        if best is None or score < best[0]:
            best = (score, rxcui)
    if best is None:
        return None, f"no available, tolerated {target_class} alternative"
    return best[1], ""


def plan_demand(
    cohort: Sequence[PatientVector],
    candidates: Sequence[str],
    on_hand: dict[str, int] | None = None,
    unavailable: Sequence[str] = (),
    units_per_patient: int = 30,
) -> tuple[dict[str, DemandLine], dict[str, int]]:
    """Aggregate a cohort into a purchasing plan.

    **Demand follows therapy, not eligibility.** A patient generates demand for
    the drugs they are actually on; the fact that they *could* tolerate six
    others is a safety statistic, not a reason to buy six others. Planning off
    eligibility puts the whole cohort on whichever safe drug happens to sort
    first, which is how this function behaved before and it was wrong.

    `unavailable` is the bridge from COMP-1: a drug that is red or in shortage
    is withdrawn, and each affected patient is re-routed to the safest **in-class**
    alternative for them individually. Patients with no such alternative are
    counted, not silently dropped — that count is the number a director needs.

    Returns the per-drug lines and a summary of what could not be served.
    """
    on_hand = on_hand or {}
    unavailable_set = {str(u) for u in unavailable}
    known = [str(r) for r in candidates]
    lines = {r: DemandLine(rxcui=r, on_hand=on_hand.get(r, 0)) for r in known}
    unserved: dict[str, int] = {}

    for patient in cohort:
        # Safety statistics across every candidate — useful to a pharmacist even
        # where it does not drive a purchase.
        for rxcui in known:
            result = assess(patient, rxcui)
            line = lines[rxcui]
            if result.verdict is Verdict.BLOCKED:
                line.blocked += 1
                for f in result.findings:
                    if f.severity is Severity.BLOCK:
                        line.reasons[f.code] = line.reasons.get(f.code, 0) + 1
                continue
            line.eligible += 1
            if result.verdict is not Verdict.GREEN:
                line.flagged += 1

        # Demand: only for therapy this patient is actually on.
        for rxcui in patient.active_rxcuis:
            rxcui = str(rxcui)
            if rxcui not in lines:
                continue  # not a drug we are planning to stock
            if rxcui not in unavailable_set:
                lines[rxcui].on_therapy += 1
                lines[rxcui].units_needed += units_per_patient
                continue
            alternative, reason = best_substitute(patient, rxcui, known, unavailable_set)
            if alternative is None:
                unserved[reason] = unserved.get(reason, 0) + 1
                continue
            lines[alternative].substitutes_for += 1
            lines[alternative].units_needed += units_per_patient

    return lines, unserved
